export const ADD_USER = "ADD_USER";
export const REMOVE_USER = "REMOVE_USER";
export const EDIT_USER = "EDIT_USER";
export const SEARCH_USERS = "SEARCH_USERS";
export const DELETE_SELECTED_USERS = "DELETE_SELECTED_USERS";
export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const SET_DELETE_USERS = "SET_DELETE_USERS";
