export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCEEDED = "ADD_USER_SUCCEEDED";
export const ADD_USER_FAILED = "ADD_USER_FAILED";

export const REMOVE_USER = "REMOVE_USER";

export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_SUCCEEDED = "EDIT_USER_SUCCEEDED";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

export const SEARCH_USERS = "SEARCH_USERS";
export const DELETE_SELECTED_USERS = "DELETE_SELECTED_USERS";
export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const SET_DELETE_USERS = "SET_DELETE_USERS";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCEEDED = "FETCH_USERS_SUCCEEDED";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";
export const GET_USERS = "GET_USERS";
export const REMOVE_USER_SUCCEEDED = "REMOVE_USER_SUCCEEDED";
export const REMOVE_USER_FAILED = "REMOVE_USER_FAILED";
